import MuiTheme from '@/theme/MuiTheme';
import './globals.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <MuiTheme>
        <body className={inter.className}>{children}</body>
      </MuiTheme>
    </html>
  );
}
