import MuiTheme from '@/theme/MuiTheme';
import './globals.scss';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';

interface RootProps {
  children: React.ReactNode;
  params: { locale: 'en' | 'fa' };
}

export function generateStaticParams() {
  return [{ locale: 'en' }, { locale: 'fa' }];
}

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, params }: RootProps) {
  let messages;
  try {
    messages = (await import(`../../messages/${params.locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang={params.locale} dir={params.locale === 'en' ? 'ltr' : 'rtl'}>
      <MuiTheme>
        <NextIntlClientProvider locale={params.locale} messages={messages}>
          <body className={inter.className}>{children}</body>
        </NextIntlClientProvider>
      </MuiTheme>
    </html>
  );
}
